# Use postgres/example user/password credentials
# correr con:
# docker-compose -f stack.yml up

# Stop con:
# docker stop postgres_adminer_1
# docker stop postgres_db_1

# Remover containers:
# docker rm postgres_adminer_1
# docker rm postgres_db_1

version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hector01
      POSTGRES_USER: hector
      POSTGRES_DB: dbempleados
    ports:
      - 5432:5432 # vinculamos el puerto de la db al del localhost

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
