# Generated by Django 3.1.2 on 2020-11-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0006_auto_20201102_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
    ]
