# Generated by Django 3.1.2 on 2020-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0009_auto_20201102_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(editable=False, max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre Corto'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
    ]
