# Generated by Django 3.1.2 on 2020-11-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0010_auto_20201102_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Mi departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
